// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoggingMessage.proto

package qgame.engine.logging.kafka;

public final class LoggingMessage {
  private LoggingMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LoggingLevel}
   */
  public enum LoggingLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(0, 1),
    /**
     * <code>WARNING = 2;</code>
     */
    WARNING(1, 2),
    /**
     * <code>INFO = 3;</code>
     */
    INFO(2, 3),
    /**
     * <code>DEBUG = 4;</code>
     */
    DEBUG(3, 4),
    ;

    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;
    /**
     * <code>WARNING = 2;</code>
     */
    public static final int WARNING_VALUE = 2;
    /**
     * <code>INFO = 3;</code>
     */
    public static final int INFO_VALUE = 3;
    /**
     * <code>DEBUG = 4;</code>
     */
    public static final int DEBUG_VALUE = 4;


    public final int getNumber() { return value; }

    public static LoggingLevel valueOf(int value) {
      switch (value) {
        case 1: return ERROR;
        case 2: return WARNING;
        case 3: return INFO;
        case 4: return DEBUG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoggingLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LoggingLevel>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoggingLevel>() {
            public LoggingLevel findValueByNumber(int number) {
              return LoggingLevel.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return qgame.engine.logging.kafka.LoggingMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoggingLevel[] VALUES = values();

    public static LoggingLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LoggingLevel(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoggingLevel)
  }

  public interface LoggingEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoggingEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .LoggingLevel level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>required .LoggingLevel level = 1;</code>
     */
    qgame.engine.logging.kafka.LoggingMessage.LoggingLevel getLevel();

    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    boolean hasHost();
    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    java.lang.String getHost();
    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>optional string source = 3;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 3;</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>optional string thread = 4;</code>
     */
    boolean hasThread();
    /**
     * <code>optional string thread = 4;</code>
     */
    java.lang.String getThread();
    /**
     * <code>optional string thread = 4;</code>
     */
    com.google.protobuf.ByteString
        getThreadBytes();

    /**
     * <code>optional string logClass = 5;</code>
     */
    boolean hasLogClass();
    /**
     * <code>optional string logClass = 5;</code>
     */
    java.lang.String getLogClass();
    /**
     * <code>optional string logClass = 5;</code>
     */
    com.google.protobuf.ByteString
        getLogClassBytes();

    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    long getTimestamp();

    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> 
        getMdcList();
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity getMdc(int index);
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    int getMdcCount();
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    java.util.List<? extends qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder> 
        getMdcOrBuilderList();
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder getMdcOrBuilder(
        int index);

    /**
     * <code>optional string message = 8;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 8;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 8;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string stackTrace = 9;</code>
     */
    boolean hasStackTrace();
    /**
     * <code>optional string stackTrace = 9;</code>
     */
    java.lang.String getStackTrace();
    /**
     * <code>optional string stackTrace = 9;</code>
     */
    com.google.protobuf.ByteString
        getStackTraceBytes();
  }
  /**
   * Protobuf type {@code LoggingEvent}
   */
  public static final class LoggingEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LoggingEvent)
      LoggingEventOrBuilder {
    // Use LoggingEvent.newBuilder() to construct.
    private LoggingEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoggingEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoggingEvent defaultInstance;
    public static LoggingEvent getDefaultInstance() {
      return defaultInstance;
    }

    public LoggingEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoggingEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              qgame.engine.logging.kafka.LoggingMessage.LoggingLevel value = qgame.engine.logging.kafka.LoggingMessage.LoggingLevel.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                level_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              host_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              source_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              thread_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              logClass_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                mdc_ = new java.util.ArrayList<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity>();
                mutable_bitField0_ |= 0x00000040;
              }
              mdc_.add(input.readMessage(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              message_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              stackTrace_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          mdc_ = java.util.Collections.unmodifiableList(mdc_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.class, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<LoggingEvent> PARSER =
        new com.google.protobuf.AbstractParser<LoggingEvent>() {
      public LoggingEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoggingEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoggingEvent> getParserForType() {
      return PARSER;
    }

    public interface LoggingMDCEntityOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LoggingEvent.LoggingMDCEntity)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code LoggingEvent.LoggingMDCEntity}
     */
    public static final class LoggingMDCEntity extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:LoggingEvent.LoggingMDCEntity)
        LoggingMDCEntityOrBuilder {
      // Use LoggingMDCEntity.newBuilder() to construct.
      private LoggingMDCEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LoggingMDCEntity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LoggingMDCEntity defaultInstance;
      public static LoggingMDCEntity getDefaultInstance() {
        return defaultInstance;
      }

      public LoggingMDCEntity getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LoggingMDCEntity(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_LoggingMDCEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_LoggingMDCEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.class, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder.class);
      }

      public static com.google.protobuf.Parser<LoggingMDCEntity> PARSER =
          new com.google.protobuf.AbstractParser<LoggingMDCEntity>() {
        public LoggingMDCEntity parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoggingMDCEntity(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LoggingMDCEntity> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LoggingEvent.LoggingMDCEntity}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LoggingEvent.LoggingMDCEntity)
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_LoggingMDCEntity_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_LoggingMDCEntity_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.class, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder.class);
        }

        // Construct using qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_LoggingMDCEntity_descriptor;
        }

        public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity getDefaultInstanceForType() {
          return qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.getDefaultInstance();
        }

        public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity build() {
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity buildPartial() {
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity result = new qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity) {
            return mergeFrom((qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity other) {
          if (other == qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:LoggingEvent.LoggingMDCEntity)
      }

      static {
        defaultInstance = new LoggingMDCEntity(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:LoggingEvent.LoggingMDCEntity)
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private qgame.engine.logging.kafka.LoggingMessage.LoggingLevel level_;
    /**
     * <code>required .LoggingLevel level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .LoggingLevel level = 1;</code>
     */
    public qgame.engine.logging.kafka.LoggingMessage.LoggingLevel getLevel() {
      return level_;
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private java.lang.Object host_;
    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string host = 2 [default = "localhost"];</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private java.lang.Object source_;
    /**
     * <code>optional string source = 3;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREAD_FIELD_NUMBER = 4;
    private java.lang.Object thread_;
    /**
     * <code>optional string thread = 4;</code>
     */
    public boolean hasThread() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string thread = 4;</code>
     */
    public java.lang.String getThread() {
      java.lang.Object ref = thread_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          thread_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string thread = 4;</code>
     */
    public com.google.protobuf.ByteString
        getThreadBytes() {
      java.lang.Object ref = thread_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thread_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGCLASS_FIELD_NUMBER = 5;
    private java.lang.Object logClass_;
    /**
     * <code>optional string logClass = 5;</code>
     */
    public boolean hasLogClass() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string logClass = 5;</code>
     */
    public java.lang.String getLogClass() {
      java.lang.Object ref = logClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string logClass = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLogClassBytes() {
      java.lang.Object ref = logClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MDC_FIELD_NUMBER = 7;
    private java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> mdc_;
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    public java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> getMdcList() {
      return mdc_;
    }
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    public java.util.List<? extends qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder> 
        getMdcOrBuilderList() {
      return mdc_;
    }
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    public int getMdcCount() {
      return mdc_.size();
    }
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity getMdc(int index) {
      return mdc_.get(index);
    }
    /**
     * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
     */
    public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder getMdcOrBuilder(
        int index) {
      return mdc_.get(index);
    }

    public static final int MESSAGE_FIELD_NUMBER = 8;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 8;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string message = 8;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STACKTRACE_FIELD_NUMBER = 9;
    private java.lang.Object stackTrace_;
    /**
     * <code>optional string stackTrace = 9;</code>
     */
    public boolean hasStackTrace() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string stackTrace = 9;</code>
     */
    public java.lang.String getStackTrace() {
      java.lang.Object ref = stackTrace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stackTrace_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stackTrace = 9;</code>
     */
    public com.google.protobuf.ByteString
        getStackTraceBytes() {
      java.lang.Object ref = stackTrace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      level_ = qgame.engine.logging.kafka.LoggingMessage.LoggingLevel.ERROR;
      host_ = "localhost";
      source_ = "";
      thread_ = "";
      logClass_ = "";
      timestamp_ = 0L;
      mdc_ = java.util.Collections.emptyList();
      message_ = "";
      stackTrace_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMdcCount(); i++) {
        if (!getMdc(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSourceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getThreadBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLogClassBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, timestamp_);
      }
      for (int i = 0; i < mdc_.size(); i++) {
        output.writeMessage(7, mdc_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getMessageBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getStackTraceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSourceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getThreadBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLogClassBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      for (int i = 0; i < mdc_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, mdc_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMessageBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getStackTraceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoggingEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoggingEvent)
        qgame.engine.logging.kafka.LoggingMessage.LoggingEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.class, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.Builder.class);
      }

      // Construct using qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMdcFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = qgame.engine.logging.kafka.LoggingMessage.LoggingLevel.ERROR;
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = "localhost";
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        thread_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        logClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (mdcBuilder_ == null) {
          mdc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          mdcBuilder_.clear();
        }
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        stackTrace_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qgame.engine.logging.kafka.LoggingMessage.internal_static_LoggingEvent_descriptor;
      }

      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent getDefaultInstanceForType() {
        return qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.getDefaultInstance();
      }

      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent build() {
        qgame.engine.logging.kafka.LoggingMessage.LoggingEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent buildPartial() {
        qgame.engine.logging.kafka.LoggingMessage.LoggingEvent result = new qgame.engine.logging.kafka.LoggingMessage.LoggingEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.thread_ = thread_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.logClass_ = logClass_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (mdcBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            mdc_ = java.util.Collections.unmodifiableList(mdc_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.mdc_ = mdc_;
        } else {
          result.mdc_ = mdcBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.stackTrace_ = stackTrace_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qgame.engine.logging.kafka.LoggingMessage.LoggingEvent) {
          return mergeFrom((qgame.engine.logging.kafka.LoggingMessage.LoggingEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent other) {
        if (other == qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000002;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000004;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasThread()) {
          bitField0_ |= 0x00000008;
          thread_ = other.thread_;
          onChanged();
        }
        if (other.hasLogClass()) {
          bitField0_ |= 0x00000010;
          logClass_ = other.logClass_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (mdcBuilder_ == null) {
          if (!other.mdc_.isEmpty()) {
            if (mdc_.isEmpty()) {
              mdc_ = other.mdc_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureMdcIsMutable();
              mdc_.addAll(other.mdc_);
            }
            onChanged();
          }
        } else {
          if (!other.mdc_.isEmpty()) {
            if (mdcBuilder_.isEmpty()) {
              mdcBuilder_.dispose();
              mdcBuilder_ = null;
              mdc_ = other.mdc_;
              bitField0_ = (bitField0_ & ~0x00000040);
              mdcBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMdcFieldBuilder() : null;
            } else {
              mdcBuilder_.addAllMessages(other.mdc_);
            }
          }
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000080;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasStackTrace()) {
          bitField0_ |= 0x00000100;
          stackTrace_ = other.stackTrace_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLevel()) {
          
          return false;
        }
        for (int i = 0; i < getMdcCount(); i++) {
          if (!getMdc(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qgame.engine.logging.kafka.LoggingMessage.LoggingEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qgame.engine.logging.kafka.LoggingMessage.LoggingEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private qgame.engine.logging.kafka.LoggingMessage.LoggingLevel level_ = qgame.engine.logging.kafka.LoggingMessage.LoggingLevel.ERROR;
      /**
       * <code>required .LoggingLevel level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .LoggingLevel level = 1;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingLevel getLevel() {
        return level_;
      }
      /**
       * <code>required .LoggingLevel level = 1;</code>
       */
      public Builder setLevel(qgame.engine.logging.kafka.LoggingMessage.LoggingLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .LoggingLevel level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = qgame.engine.logging.kafka.LoggingMessage.LoggingLevel.ERROR;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "localhost";
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2 [default = "localhost"];</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 3;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object thread_ = "";
      /**
       * <code>optional string thread = 4;</code>
       */
      public boolean hasThread() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string thread = 4;</code>
       */
      public java.lang.String getThread() {
        java.lang.Object ref = thread_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            thread_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string thread = 4;</code>
       */
      public com.google.protobuf.ByteString
          getThreadBytes() {
        java.lang.Object ref = thread_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thread_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string thread = 4;</code>
       */
      public Builder setThread(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        thread_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string thread = 4;</code>
       */
      public Builder clearThread() {
        bitField0_ = (bitField0_ & ~0x00000008);
        thread_ = getDefaultInstance().getThread();
        onChanged();
        return this;
      }
      /**
       * <code>optional string thread = 4;</code>
       */
      public Builder setThreadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        thread_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logClass_ = "";
      /**
       * <code>optional string logClass = 5;</code>
       */
      public boolean hasLogClass() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string logClass = 5;</code>
       */
      public java.lang.String getLogClass() {
        java.lang.Object ref = logClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logClass = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLogClassBytes() {
        java.lang.Object ref = logClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logClass = 5;</code>
       */
      public Builder setLogClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        logClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logClass = 5;</code>
       */
      public Builder clearLogClass() {
        bitField0_ = (bitField0_ & ~0x00000010);
        logClass_ = getDefaultInstance().getLogClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logClass = 5;</code>
       */
      public Builder setLogClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        logClass_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> mdc_ =
        java.util.Collections.emptyList();
      private void ensureMdcIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          mdc_ = new java.util.ArrayList<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity>(mdc_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder> mdcBuilder_;

      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> getMdcList() {
        if (mdcBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mdc_);
        } else {
          return mdcBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public int getMdcCount() {
        if (mdcBuilder_ == null) {
          return mdc_.size();
        } else {
          return mdcBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity getMdc(int index) {
        if (mdcBuilder_ == null) {
          return mdc_.get(index);
        } else {
          return mdcBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder setMdc(
          int index, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity value) {
        if (mdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMdcIsMutable();
          mdc_.set(index, value);
          onChanged();
        } else {
          mdcBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder setMdc(
          int index, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder builderForValue) {
        if (mdcBuilder_ == null) {
          ensureMdcIsMutable();
          mdc_.set(index, builderForValue.build());
          onChanged();
        } else {
          mdcBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder addMdc(qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity value) {
        if (mdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMdcIsMutable();
          mdc_.add(value);
          onChanged();
        } else {
          mdcBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder addMdc(
          int index, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity value) {
        if (mdcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMdcIsMutable();
          mdc_.add(index, value);
          onChanged();
        } else {
          mdcBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder addMdc(
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder builderForValue) {
        if (mdcBuilder_ == null) {
          ensureMdcIsMutable();
          mdc_.add(builderForValue.build());
          onChanged();
        } else {
          mdcBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder addMdc(
          int index, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder builderForValue) {
        if (mdcBuilder_ == null) {
          ensureMdcIsMutable();
          mdc_.add(index, builderForValue.build());
          onChanged();
        } else {
          mdcBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder addAllMdc(
          java.lang.Iterable<? extends qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity> values) {
        if (mdcBuilder_ == null) {
          ensureMdcIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mdc_);
          onChanged();
        } else {
          mdcBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder clearMdc() {
        if (mdcBuilder_ == null) {
          mdc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          mdcBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public Builder removeMdc(int index) {
        if (mdcBuilder_ == null) {
          ensureMdcIsMutable();
          mdc_.remove(index);
          onChanged();
        } else {
          mdcBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder getMdcBuilder(
          int index) {
        return getMdcFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder getMdcOrBuilder(
          int index) {
        if (mdcBuilder_ == null) {
          return mdc_.get(index);  } else {
          return mdcBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public java.util.List<? extends qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder> 
           getMdcOrBuilderList() {
        if (mdcBuilder_ != null) {
          return mdcBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mdc_);
        }
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder addMdcBuilder() {
        return getMdcFieldBuilder().addBuilder(
            qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder addMdcBuilder(
          int index) {
        return getMdcFieldBuilder().addBuilder(
            index, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .LoggingEvent.LoggingMDCEntity mdc = 7;</code>
       */
      public java.util.List<qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder> 
           getMdcBuilderList() {
        return getMdcFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder> 
          getMdcFieldBuilder() {
        if (mdcBuilder_ == null) {
          mdcBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntity.Builder, qgame.engine.logging.kafka.LoggingMessage.LoggingEvent.LoggingMDCEntityOrBuilder>(
                  mdc_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          mdc_ = null;
        }
        return mdcBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 8;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 8;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stackTrace_ = "";
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public boolean hasStackTrace() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public java.lang.String getStackTrace() {
        java.lang.Object ref = stackTrace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stackTrace_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public com.google.protobuf.ByteString
          getStackTraceBytes() {
        java.lang.Object ref = stackTrace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stackTrace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public Builder setStackTrace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        stackTrace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public Builder clearStackTrace() {
        bitField0_ = (bitField0_ & ~0x00000100);
        stackTrace_ = getDefaultInstance().getStackTrace();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stackTrace = 9;</code>
       */
      public Builder setStackTraceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        stackTrace_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoggingEvent)
    }

    static {
      defaultInstance = new LoggingEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoggingEvent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoggingEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoggingEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoggingEvent_LoggingMDCEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoggingEvent_LoggingMDCEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LoggingMessage.proto\"\214\002\n\014LoggingEvent\022" +
      "\034\n\005level\030\001 \002(\0162\r.LoggingLevel\022\027\n\004host\030\002 " +
      "\001(\t:\tlocalhost\022\016\n\006source\030\003 \001(\t\022\016\n\006thread" +
      "\030\004 \001(\t\022\020\n\010logClass\030\005 \001(\t\022\021\n\ttimestamp\030\006 " +
      "\001(\003\022+\n\003mdc\030\007 \003(\0132\036.LoggingEvent.LoggingM" +
      "DCEntity\022\017\n\007message\030\010 \001(\t\022\022\n\nstackTrace\030" +
      "\t \001(\t\032.\n\020LoggingMDCEntity\022\013\n\003key\030\001 \002(\t\022\r" +
      "\n\005value\030\002 \002(\t*;\n\014LoggingLevel\022\t\n\005ERROR\020\001" +
      "\022\013\n\007WARNING\020\002\022\010\n\004INFO\020\003\022\t\n\005DEBUG\020\004B\036\n\032qg" +
      "ame.engine.logging.kafkaH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoggingEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoggingEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoggingEvent_descriptor,
        new java.lang.String[] { "Level", "Host", "Source", "Thread", "LogClass", "Timestamp", "Mdc", "Message", "StackTrace", });
    internal_static_LoggingEvent_LoggingMDCEntity_descriptor =
      internal_static_LoggingEvent_descriptor.getNestedTypes().get(0);
    internal_static_LoggingEvent_LoggingMDCEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoggingEvent_LoggingMDCEntity_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
